# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Minimal
email: santana.pauloh@gmail.com
description: Let's go to do a simple test using JEKYLL!!.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  santanapaulo

# Build settings
markdown: kramdown
# permalink: /:categories/:month/:day/:title
permalink: /:title